services:
  - type: web
    name: sonicwave
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 10000
